Add Gitllab CI to Coverage
JuliaCI/Coverage.jl pull request #331
Opened 2022-05-19 23:04 UTC by theogf

This allows to directly submit the Coverage report to Codecov or Coveralls from a Gitlab action.
This solves #330

2022-05-20 07:17 UTC, maleadt commented
There's tests for the other providers, so this PR better needs some as well.

2022-05-23 08:51 UTC, maleadt requested changes

2022-05-23 08:51 UTC, maleadt commented on test/runtests.jl
> +        # test Travis
Why duplicate this?

2022-05-23 08:51 UTC, maleadt commented on test/runtests.jl
> +        # test Travis
Why duplicate this?

2022-05-23 08:51 UTC, maleadt commented on test/runtests.jl
> +                # test circle ci submission process
Wrong comment?

2022-05-23 09:42 UTC, maleadt commented
OK, I've moved it back to draft.

2022-05-23 09:47 UTC, theogf commented
Ok sorry for the whole CI mess! Testing this kind of stuff is really painful! I can now confirm it works for both push on master/main and merge requests (Gitlab name for PRs)

2022-05-23 10:10 UTC, theogf commented
It should now be ready for merging. As said above you can check how it looks on  https://gitlab.com/theogf/testpackage.jl/-/tree/main

2022-05-23 11:38 UTC, theogf commented
Not sure about the bump on the Project.toml, should it be 1.5.0 or 1.4.1 ?

2022-05-24 13:23 UTC, maleadt commented
Since this is a new features, 1.5.0 would be best.

2022-05-24 21:22 UTC, merged